relative = {
  "layout_above", "layout_alignBaseline", "layout_alignBottom", "layout_alignEnd", "layout_alignLeft", "layout_alignParentBottom", "layout_alignParentEnd", "layout_alignParentLeft", "layout_alignParentRight", "layout_alignParentStart", "layout_alignParentTop", "layout_alignRight", "layout_alignStart", "layout_alignTop", "layout_alignWithParentIfMissing", "layout_below", "layout_centerHorizontal", "layout_centerInParent", "layout_centerVertical", "layout_toEndOf", "layout_toLeftOf", "layout_toRightOf", "layout_toStartOf"
}

fds_grid = {
  "添加", "删除", "复制", "上移", "下移", "父控件", "子控件",
  "id", "orientation",
  "columnCount", "rowCount",
  "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor", "gravity",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
}

fds_linear = {
  "添加", "删除", "复制", "上移", "下移", "父控件", "子控件",
  "id", "orientation", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "fitsSystemWindows",
  "background", "backgroundColor", "gravity",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
  "weightSum", "divider", "showDividers",
}

fds_group = {
  "添加", "删除", "复制", "上移", "下移", "父控件", "子控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "fitsSystemWindows",
  "background", "backgroundColor", "gravity",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "CardElevation", "radius", "strokeWidth", "strokeColor",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
}

fds_text = {
  "删除", "复制", "上移", "下移", "父控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor", "text", "ellipsize",
  "hint", "textColor", "hintTextColor", "textSize", "singleLine", "maxLines", "maxEms", "maxHeight", "maxWidth", "minWidth", "gravity",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "CardElevation", "radius",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
  "textStyle", "typeface", "letterSpacing", "lineSpacingExtra", "includeFontPadding",
  "inputType", "imeOptions", "maxLength",
}

fds_image = {
  "删除", "复制", "上移", "下移", "父控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor", "src", "scaleType", "adjustViewBounds", "tint",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
}

fds_progress = {
  "删除", "复制", "上移", "下移", "父控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "background", "backgroundColor",
  "progress", "max", "indeterminate", "progressTint", "indeterminateTint",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "elevation", "alpha", "visibility", "enabled",
}

fds_material = {
  "添加", "删除", "复制", "上移", "下移", "父控件", "子控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor", "text", "hint", "textColor", "hintTextColor", "textSize",
  "icon", "iconGravity", "iconPadding", "iconTint", "src", "tint",
  "strokeWidth", "strokeColor", "radius", "CardElevation", "elevation",
  "checked", "checkable", "enabled", "clickable", "focusable",
  "valueFrom", "valueTo", "value", "stepSize",
  "boxBackgroundMode", "endIconMode", "startIconDrawable", "helperText", "error", "counterEnabled", "counterMaxLength",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "alpha", "visibility", "gravity", "orientation",
  "title", "subtitle", "menu",
}


fds_view = {
  "删除", "复制", "上移", "下移", "父控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "Rotation", "RotationX", "RotationY",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
}

fds_abs = {
  "删除", "复制", "上移", "下移", "父控件",
  "id", "layout_width", "layout_height", "layout_gravity",
  "onClick", "onLongClick",
  "background", "backgroundColor",
  "layout_margin", "layout_marginLeft", "layout_marginTop", "layout_marginRight", "layout_marginBottom",
  "padding", "paddingLeft", "paddingTop", "paddingRight", "paddingBottom",
  "elevation", "alpha", "visibility", "enabled", "clickable", "focusable",
}

ns = {
  "Basic Controls",
  "Selection/Switch Controls",
  "List & Pagination Controls",
  "Data Input & Display Controls",
  "Layout Containers",
  "Material Components",
  "Material Navigation",
  "Material Feedback",
  "Navigation & Action Controls",
  "Progress & Indicators",
  "Special Views",
  "Date & Time Controls"
}

wds = {
  {
    "AppCompatButton",
    "AppCompatEditText",
    "AppCompatTextView",
    "AppCompatImageView",
    "AppCompatImageButton",
    "CircleImageView",
    "TextView",
    "EditText",
    "Button",
    "ImageButton",
    "ImageView",
    "CheckedTextView",
    "Space"
  },
  {
    "AppCompatCheckBox",
    "AppCompatRadioButton",
    "AppCompatToggleButton",
    "SwitchMaterial",
    "MaterialSwitch",
    "MaterialCheckBox",
    "MaterialRadioButton",
    "CheckBox",
    "RadioButton",
    "ToggleButton",
    "Switch",
    "RatingBar"
  },
  {
    "RecyclerView",
    "ListView",
    "ExpandableListView",
    "ViewPager",
    "ViewPager2",
    "AppCompatSpinner",
    "GridView",
    "HorizontalListView",
    "PageView",
    "PageLayout",
    "ExListView",
    "FlexibleListView",
    "StackView",
    "Spinner"
  },
  {
    "SeekBar",
    "ProgressBar",
    "NumberPicker",
    "AutoCompleteTextView",
    "AppCompatAutoCompleteTextView",
    "AppCompatMultiAutoCompleteTextView",
    "SearchView",
    "TextInputLayout",
    "TextInputEditText",
    "MaterialAutoCompleteTextView",
    "NumberProgressBar",
    "MultiAutoCompleteTextView",
    "TextClock",
    "Chronometer",
    "QuickContactBadge"
  },
  {
    "LinearLayout",
    "FrameLayout",
    "RelativeLayout",
    "ConstraintLayout",
    "CoordinatorLayout",
    "CardView",
    "GridLayout",
    "ScrollView",
    "HorizontalScrollView",
    "NestedScrollView",
    "AbsoluteLayout",
    "TableLayout",
    "TableRow",
    "SwipeRefreshLayout",
    "SlidingPaneLayout",
    "ViewAnimator",
    "ViewFlipper",
    "ViewSwitcher",
    "DrawerLayout"
  },
  {
    "MaterialButton",
    "MaterialTextView",
    "MaterialTextField",
    "MaterialCardView",
    "MaterialToolbar",
    "TextInputLayout",
    "TextInputEditText",
    "MaterialAutoCompleteTextView",
    "Chip",
    "ChipGroup",
    "MaterialSwitch",
    "SwitchMaterial",
    "MaterialCheckBox",
    "MaterialRadioButton",
    "MaterialButtonToggleGroup",
    "MaterialButtonGroup",
    "Slider",
    "RangeSlider",
    "MaterialDivider",
    "ShapeableImageView",
    "FloatingActionButton",
    "ExtendedFloatingActionButton",
    "SearchBar",
    "MaterialSearchView",
    "LoadingIndicator",
    "FloatingToolbarLayout"
  },
  {
    "AppBarLayout",
    "CollapsingToolbarLayout",
    "MaterialToolbar",
    "BottomAppBar",
    "BottomNavigationView",
    "NavigationView",
    "NavigationRailView",
    "TabLayout",
    "TabItem",
    "SearchBar",
    "MaterialSearchView"
  },
  {
    "LinearProgressIndicator",
    "CircularProgressIndicator",
    "LoadingIndicator",
    "Slider",
    "RangeSlider",
    "MaterialDivider"
  },
  {
    "Toolbar",
    "MaterialToolbar",
    "SearchBar",
    "BottomNavigationView",
    "NavigationView",
    "NavigationRailView",
    "TabHost",
    "TabWidget",
    "ZoomButton",
    "ZoomControls"
  },
  {
    "ProgressBar",
    "LinearProgressIndicator",
    "CircularProgressIndicator",
    "SeekBar",
    "NumberProgressBar",
    "LoadingIndicator"
  },
  {
    "VideoView",
    "WebView",
    "AnalogClock",
    "PullingLayout",
  },
  {
    "DatePicker",
    "TimePicker",
    "CalendarView"
  }
}

wds2 = {
  {
    "兼容包按钮",
    "兼容包编辑框",
    "兼容包文本视图",
    "兼容包图片视图",
    "兼容包图片按钮",
    "圆形图片视图",
    "文本视图",
    "编辑框",
    "按钮",
    "图片按钮",
    "图片视图",
    "可选中文本",
    "占位空白"
  },
  {
    "兼容包复选框",
    "兼容包单选按钮",
    "兼容包切换按钮",
    "Material 开关(旧)",
    "Material 开关",
    "Material 复选框",
    "Material 单选按钮",
    "复选框",
    "单选按钮",
    "切换按钮",
    "开关",
    "评分条"
  },
  {
    "循环视图",
    "列表视图",
    "可展开列表视图",
    "视图分页器",
    "视图分页器2",
    "兼容包下拉列表",
    "网格视图",
    "水平列表视图",
    "页面视图",
    "页面布局",
    "可扩展列表视图",
    "灵活列表视图",
    "栈视图",
    "下拉列表"
  },
  {
    "拖动条",
    "进度条",
    "数字选择器",
    "自动完成文本视图",
    "兼容包自动完成文本视图",
    "兼容包多自动完成文本视图",
    "搜索视图",
    "文本输入布局",
    "文本输入编辑文本",
    "Material 自动完成输入",
    "数字进度条",
    "多自动完成文本视图",
    "文本时钟",
    "计时器",
    "快速联系人徽章"
  },
  {
    "线性布局",
    "帧布局",
    "相对布局",
    "约束布局",
    "协调布局",
    "卡片视图",
    "网格布局",
    "滚动视图",
    "水平滚动视图",
    "嵌套滚动视图",
    "绝对布局",
    "表格布局",
    "表格行",
    "下拉刷新布局",
    "滑动面板布局",
    "视图动画器",
    "视图翻转器",
    "视图切换器",
    "抽屉布局"
  },
  {
    "Material 按钮",
    "Material 文本视图",
    "Material 文本输入框",
    "Material 卡片",
    "Material 工具栏",
    "文本输入布局",
    "文本输入编辑文本",
    "Material 自动完成输入",
    "芯片 Chip",
    "芯片组 ChipGroup",
    "Material 开关",
    "Material 开关(旧)",
    "Material 复选框",
    "Material 单选按钮",
    "按钮切换组",
    "Material 按钮组",
    "滑块 Slider",
    "范围滑块",
    "Material 分割线",
    "可塑形图片",
    "悬浮操作按钮 FAB",
    "扩展 FAB",
    "搜索栏 SearchBar",
    "Material 搜索视图",
    "加载指示器",
    "悬浮工具栏布局"
  },
  {
    "应用栏布局 AppBar",
    "折叠工具栏布局",
    "Material 工具栏",
    "底部应用栏",
    "底部导航栏",
    "侧边导航视图",
    "导航栏轨 NavigationRail",
    "标签布局 TabLayout",
    "标签项 TabItem",
    "搜索栏 SearchBar",
    "Material 搜索视图"
  },
  {
    "线性进度指示器",
    "圆形进度指示器",
    "加载指示器",
    "滑块 Slider",
    "范围滑块",
    "Material 分割线"
  },
  {
    "工具栏",
    "Material 工具栏",
    "搜索栏",
    "底部导航栏",
    "侧边导航视图",
    "导航栏轨",
    "标签宿主",
    "标签组件",
    "缩放按钮",
    "缩放控件"
  },
  {
    "进度条",
    "线性进度指示器",
    "圆形进度指示器",
    "拖动条",
    "数字进度条",
    "加载指示器"
  },
  {
    "视频视图",
    "网页视图",
    "模拟时钟",
    "下拉布局"
  },
  {
    "日期选择器",
    "时间选择器",
    "日历视图"
  }
}

ns2 = {
  "基础控件",
  "选择/开关控件",
  "列表与分页控件",
  "数据输入与展示",
  "布局容器",
  "Material 组件",
  "Material 导航",
  "Material 反馈/进度",
  "导航与操作",
  "进度与指示器",
  "特殊视图",
  "日期与时间"
}

CAN_HAVE_CHILDREN = {
  LinearLayoutCompat,
  Toolbar,
  MaterialCardView,
  TextInputLayout,
  ChipGroup,
  TabLayout,
  AppBarLayout,
  CollapsingToolbarLayout,
  ConstraintLayout,
  CoordinatorLayout,
  DrawerLayout,
  GridLayout,
  SwipeRefreshLayout,
  SlidingPaneLayout,
  ViewPager,
  ViewPager2,
  NestedScrollView,
  MaterialButtonToggleGroup,
  MaterialButtonGroup,
  BottomAppBar,
  CardView,
  AbsoluteLayout,
  FrameLayout,
  GridLayout,
  LinearLayout,
  RelativeLayout,
  TableLayout,
  TableRow,
  ViewAnimator,
  ViewFlipper,
  ViewSwitcher,
  HorizontalScrollView,
  ScrollView,
  ListView,
  GridView,
  ExpandableListView,
  RadioGroup,
  TabHost,
  PullingLayout,
  PageLayout,
  NavigationView,
  NavigationRailView,
  FloatingToolbarLayout,
}

TEXTVIEW_COMPAT = {
  AppCompatTextView,
  MaterialTextView,
  AppCompatEditText,
  TextInputEditText,
  MaterialAutoCompleteTextView,
  AppCompatAutoCompleteTextView,
  AppCompatMultiAutoCompleteTextView,
  AppCompatCheckedTextView,
  AppCompatButton,
  MaterialButton,
  MaterialRadioButton,
  MaterialCheckBox,
  AppCompatCheckBox,
  AppCompatRadioButton,
  AppCompatToggleButton,
  SwitchMaterial,
  MaterialSwitch,
  Chronometer,
  TextClock,
  CheckedTextView,
  EditText,
  AutoCompleteTextView,
  MultiAutoCompleteTextView,
  TextView,
  Button,
  RadioButton,
  CheckBox,
  ToggleButton,
  Switch,
  Chip,
}

IMAGEVIEW_COMPAT = {
  AppCompatImageView,
  AppCompatImageButton,
  ImageView,
  ImageButton,
  CircleImageView,
  ShapeableImageView,
  QuickContactBadge,
  FloatingActionButton,
  ExtendedFloatingActionButton,
}

LINEARLAYOUT_COMPAT = {
  LinearLayout,
  LinearLayoutCompat,
  RadioGroup,
  TabHost,
  AppBarLayout,
  MaterialButtonToggleGroup,
  MaterialButtonGroup,
  BottomAppBar,
  BottomNavigationView,
  ChipGroup,
  NavigationRailView,
}


MATERIAL_COMPAT = {
  MaterialButton,
  MaterialTextView,
  MaterialTextField,
  MaterialCardView,
  MaterialToolbar,
  MaterialSwitch,
  SwitchMaterial,
  MaterialCheckBox,
  MaterialRadioButton,
  MaterialButtonToggleGroup,
  MaterialButtonGroup,
  MaterialDivider,
  MaterialAutoCompleteTextView,
  Chip,
  ChipGroup,
  Slider,
  RangeSlider,
  ShapeableImageView,
  FloatingActionButton,
  ExtendedFloatingActionButton,
  SearchBar,
  LoadingIndicator,
  LinearProgressIndicator,
  CircularProgressIndicator,
  FloatingToolbarLayout,
  NavigationRailView,
  BottomNavigationView,
  NavigationView,
  TabLayout,
  AppBarLayout,
  CollapsingToolbarLayout,
  BottomAppBar,
  TextInputLayout,
  TextInputEditText,
}
